[project]
name = "krunner-keepassxc"
version = "1.9.1"
description = ""
authors = [{ name = "naglfar", email = "stefan@mtztech.info" }]
requires-python = ">=3.14,<4"
dependencies = [
    "dbus-python>=1.3.2",
    "cryptography>=43.0.3",
    "setproctitle>=1.3.3",
    "xdg>=6.0.0",
    "pyotp>=2.9.0",
    "dbus-fast>=2.24.4",
]

[project.scripts]
runner = "krunner_keepassxc.__main__:runner"
cli = "krunner_keepassxc.__main__:main"

[dependency-groups]
dev = [
    "pytest>=7.3.1",
    "shiv>=1.0.3",
    "radon>=6.0.1",
    "mypy>=1.3.0",
    "taskipy>=1.11.0",
    "pylint>=2.17.7",
    "rope>=1.8.0",
    "bandit>=1.7.5",
]

[tool.uv]
default-groups = "all"

[tool.taskipy.tasks]
tests = "python -m unittest tests/test_*.py"
mypy = "mypy --ignore-missing-imports --check-untyped-defs src/krunner_keepassxc tests"
lint = "pylint src/krunner_keepassxc"
radon = "radon cc src/krunner_keepassxc"
shiv = """shiv \
		-p "/usr/bin/env python3" \
		-e krunner_keepassxc.__main__:main \
		--output-file dist/krunner-keepassxc.pyz \
		."""
store = """tar czf dist/krunner-keepassxc-store-1.9.1.tar.gz --xform s:^.*/:: install/kdestore/* dist/krunner-keepassxc.pyz"""

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
