[tool.poetry]
name = "krunner-keepassxc"
version = "1.5.2"
description = ""
authors = ["naglfar <stefan@mtztech.info>"]

[tool.poetry.dependencies]
python = "^3.6,<3.11"
dbus-python = "^1.2.18"
cryptography = "^36.0.2"
setproctitle = "^1.2.3"

[tool.poetry.dev-dependencies]
vext = "0.7.6"
"vext.gi" = "0.7.4"
pytest = "7.0.1"
shiv = "1.0.1"
radon = "5.1.0"
taskipy = "1.10.1"
mypy = "0.942"
pylint = "2.12.0"
rope = "1.0.0"
bandit = "1.7.1"

[tool.poetry.scripts]
runner = "krunner_keepassxc.__main__:main"
cli = "krunner_keepassxc.__main__:cli"

[tool.taskipy.tasks]
tests = "python -m unittest tests/test_*.py"
mypy = "mypy --ignore-missing-imports --check-untyped-defs krunner_keepassxc tests"
lint = "pylint krunner_keepassxc"
radon = "radon cc krunner_keepassxc"
shiv = """shiv \
		-p "/usr/bin/env python3" \
		-e krunner_keepassxc.__main__:main \
		--output-file dist/krunner-keepassxc.pyz \
		."""
store = """tar czf dist/krunner-keepassxc.tar.gz --xform s:^.*/:: install/kdestore/* dist/krunner-keepassxc.pyz"""

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

